/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminEvent: typeof import('./src/components/AdminEvent.vue')['default']
    AdminGetMovie: typeof import('./src/components/AdminGetMovie.vue')['default']
    AdminGetShow: typeof import('./src/components/AdminGetShow.vue')['default']
    AdminHome: typeof import('./src/components/AdminHome.vue')['default']
    AdminLogin: typeof import('./src/components/AdminLogin.vue')['default']
    AdminNavBar: typeof import('./src/components/AdminNavBar.vue')['default']
    AdminSummery: typeof import('./src/components/AdminSummery.vue')['default']
    BookingDateTime: typeof import('./src/components/BookingDateTime.vue')['default']
    BookingShow: typeof import('./src/components/BookingShow.vue')['default']
    CreateEvent: typeof import('./src/components/CreateEvent.vue')['default']
    CreateMovie: typeof import('./src/components/CreateMovie.vue')['default']
    CreateShow: typeof import('./src/components/CreateShow.vue')['default']
    CreateTheatre: typeof import('./src/components/CreateTheatre.vue')['default']
    CreateVenue: typeof import('./src/components/CreateVenue.vue')['default']
    DownloadFile: typeof import('./src/components/DownloadFile.vue')['default']
    DynamicForm: typeof import('./src/components/DynamicForm.vue')['default']
    ErrorPage404: typeof import('./src/components/ErrorPage404.vue')['default']
    EventBooking: typeof import('./src/components/EventBooking.vue')['default']
    ForgetPassword: typeof import('./src/components/ForgetPassword.vue')['default']
    GetPoster: typeof import('./src/components/GetPoster.vue')['default']
    Landing: typeof import('./src/components/Landing.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MovieBooking: typeof import('./src/components/MovieBooking.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sample: typeof import('./src/components/Sample.vue')['default']
    StarRating: typeof import('./src/components/StarRating.vue')['default']
    StarRating2: typeof import('./src/components/StarRating2.vue')['default']
    SummeryBarChart: typeof import('./src/components/SummeryBarChart.vue')['default']
    SummeryLineChart: typeof import('./src/components/SummeryLineChart.vue')['default']
    Unauthorized: typeof import('./src/components/Unauthorized.vue')['default']
    UpdateEvent: typeof import('./src/components/UpdateEvent.vue')['default']
    UpdateMovie: typeof import('./src/components/UpdateMovie.vue')['default']
    UpdateShow: typeof import('./src/components/UpdateShow.vue')['default']
    UpdateTheatre: typeof import('./src/components/UpdateTheatre.vue')['default']
    UpdateVenue: typeof import('./src/components/UpdateVenue.vue')['default']
    UserBookings: typeof import('./src/components/UserBookings.vue')['default']
    UserEvent: typeof import('./src/components/UserEvent.vue')['default']
    UserEventBooking: typeof import('./src/components/UserEventBooking.vue')['default']
    UserEvents: typeof import('./src/components/UserEvents.vue')['default']
    UserHome: typeof import('./src/components/UserHome.vue')['default']
    UserLogin: typeof import('./src/components/UserLogin.vue')['default']
    UserNavBar: typeof import('./src/components/UserNavBar.vue')['default']
    UserRegister: typeof import('./src/components/UserRegister.vue')['default']
  }
}
